In [1]:
import numpy

def matrix_factorization(R, P, Q, K, steps=5000, alpha=0.0002, beta=0.02):
    '''
    R: rating matrix
    P: |U| * K (User features matrix)
    Q: |D| * K (Item features matrix)
    K: latent features
    steps: iterations
    alpha: learning rate
    beta: regularization parameter'''
    Q = Q.T

    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    # calculate error
                    eij = R[i][j] - numpy.dot(P[i,:],Q[:,j])

                    for k in range(K):
                        # calculate gradient with a and beta parameter
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])

        eR = numpy.dot(P,Q)

        e = 0

        for i in range(len(R)):

            for j in range(len(R[i])):

                if R[i][j] > 0:

                    e = e + pow(R[i][j] - numpy.dot(P[i,:],Q[:,j]), 2)

                    for k in range(K):

                        e = e + (beta/2) * (pow(P[i][k],2) + pow(Q[k][j],2))
        # 0.001: local minimum
        if e < 0.001:

            break

    return P, Q.T

In [2]:
R = [

     [5,3,0,1],

     [4,0,0,1],

     [1,1,0,5],

     [1,0,0,4],

     [0,1,5,4],

     [2,1,3,0],

    ]

R = numpy.array(R)
# N: num of User
N = len(R)
# M: num of Movie
M = len(R[0])
# Num of Features
K = 3


P = numpy.random.rand(N,K)
Q = numpy.random.rand(M,K)



nP, nQ = matrix_factorization(R, P, Q, K)

nR = numpy.dot(nP, nQ.T)

print(R)
print(nR)

[[5 3 0 1]
 [4 0 0 1]
 [1 1 0 5]
 [1 0 0 4]
 [0 1 5 4]
 [2 1 3 0]]
[[4.98786081 2.95835383 2.86987433 1.00096773]
 [3.98008995 2.29889376 2.56024056 0.99770945]
 [1.02417405 0.9556532  5.27845921 4.96396335]
 [0.99910076 0.59787308 4.55805225 3.97543148]
 [1.82094392 1.02158102 4.96122645 4.01579389]
 [1.94636356 1.06394747 2.99971086 2.08666154]]


In [4]:
def calculate_rmse(R, P, Q):
    """
    Calculate Root Mean Square Error (RMSE) between the original and predicted ratings.
    """
    e = 0
    count = 0
    for i in range(len(R)):
        for j in range(len(R[i])):
            if R[i][j] > 0:
                e += pow(R[i][j] - numpy.dot(P[i, :], Q[:, j]), 2)
                count += 1
    rmse = numpy.sqrt(e / count)
    return rmse

# Call the matrix_factorization function
nP, nQ = matrix_factorization(R, P, Q, K)

# Calculate RMSE
rmse = calculate_rmse(R, nP, nQ.T)

# Print the RMSE
print(f"Root Mean Square Error: {rmse}")


Root Mean Square Error: 0.01750435235650004
